# -*- coding: utf-8 -*-
"""mumbai-house-price-data-clean-deployement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AF1OBFDWnszrJLgoYgKW5ytThtWbMhx8
"""

import streamlit as st
import pandas as pd
import joblib

# Load model
model = joblib.load("mumbai_house_price_model.pkl")

st.title("Mumbai House Price Prediction")

area = st.number_input("Area", min_value=1)
locality = st.number_input("Locality Code", min_value=0)
city = st.number_input("City Code", min_value=0)
property_type = st.number_input("Property Type Code", min_value=0)
bedroom_num = st.number_input("Bedrooms", min_value=0)
bathroom_num = st.number_input("Bathrooms", min_value=0)
balcony_num = st.number_input("Balconies", min_value=0)
furnished = st.number_input("Furnished Code", min_value=0)
age = st.number_input("Age", min_value=0)
total_floors = st.number_input("Total Floors", min_value=1)
latitude = st.number_input("Latitude")
longitude = st.number_input("Longitude")

if st.button("Predict Price"):

    data = pd.DataFrame({
        "area": [area],
        "locality": [locality],
        "city": [city],
        "property_type": [property_type],
        "bedroom_num": [bedroom_num],
        "bathroom_num": [bathroom_num],
        "balcony_num": [balcony_num],
        "furnished": [furnished],
        "age": [age],
        "total_floors": [total_floors],
        "latitude": [latitude],
        "longitude": [longitude]
    })

    prediction = model.predict(data)

    print("Predicted House Price:", prediction[0])

    st.success(f"Predicted House Price: ₹{prediction[0]:,.2f}")